# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: FirstJob
        steps:
        - bash: echo Build FirstJob
      - job: SecondJob
        steps:
        - bash: echo Build SeconJob

  - stage: DevDeploy
    dependsOn: Build
    jobs:
      - job: DevDeployJOb
        steps:
        - bash: echo DevDeployJOb

  - stage: QADeploy
    dependsOn: DevDeploy
    jobs:
      - job: QADeployJOb
        steps:
        - bash: echo QADeployJOb
  - stage: ProdDeploy
    dependsOn:
    - DevDeploy
    - QADeploy
    
    jobs:
      - job: ProdDeployJOb
        steps:
        - bash: echo ProdDeployJOb

